### ISSUE TITLE
Build networked Instantiation of the players

### ISSUE THREAD

**Issue by Adil-Bo** [DonnAngello/Game#4]

**Comment by DonnAngello** [comment]
Not working
1 Updated camera logic.
2 Script with OnPhotonInstantiate must be attached to the root of the instantiated object.
3 After fixing that issue with avatar instantiation still persists.
4. After adding  options.PlayerTtl disconnecting issue still persists.

**Comment by Adil-Bo** [comment]
Feel free to create separate issues for 

- Camera instantiation logic
- Users timeout disconnections
